context:
  version: "48.5.0"

package:
  name: vercel-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/vercel/-/vercel-${{ version }}.tgz
  sha256: bbdd66fe00b7f52d32f1bcf6f4ab797f054630cb660a01a97478c3ad89d86e70

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - vercel help 2>&1 | grep -q "Vercel CLI ${{ version }}"

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Vercel's frontend cloud gives developers frameworks, workflows, and infrastructure to build a faster, more personalized web."
  homepage: https://github.com/vercel/vercel
  repository: https://github.com/vercel/vercel

extra:
  recipe-maintainers:
    - danielnachun
