context:
  version: "47.0.7"

package:
  name: vercel-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/vercel/-/vercel-${{ version }}.tgz
  sha256: e01632f21370f46e22f3df4f5b9003c57faff9f4c6e1fc75fb3a1689e0f17bfc

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - vercel help 2>&1 | grep -q "Vercel CLI ${{ version }}"

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Vercel's frontend cloud gives developers frameworks, workflows, and infrastructure to build a faster, more personalized web."
  homepage: https://github.com/vercel/vercel
  repository: https://github.com/vercel/vercel

extra:
  recipe-maintainers:
    - danielnachun
