context:
  version: "48.2.7"

package:
  name: vercel-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/vercel/-/vercel-${{ version }}.tgz
  sha256: 854803e605066292254706b121c1f4ed8153ec59844e4916425b4b72be2adc41

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - vercel help 2>&1 | grep -q "Vercel CLI ${{ version }}"

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Vercel's frontend cloud gives developers frameworks, workflows, and infrastructure to build a faster, more personalized web."
  homepage: https://github.com/vercel/vercel
  repository: https://github.com/vercel/vercel

extra:
  recipe-maintainers:
    - danielnachun
