context:
  version: "63.1.2"

package:
  name: vercel-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/vercel/-/vercel-${{ version }}.tgz
  sha256: d0f688e150204c24a09d41e3370062ea8a9413f579488ea76ef54362fe427cd7

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - vercel help 2>&1 | grep -q "Vercel CLI ${{ version }}"

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Vercel's frontend cloud gives developers frameworks, workflows, and infrastructure to build a faster, more personalized web."
  homepage: https://github.com/vercel/vercel
  repository: https://github.com/vercel/vercel

extra:
  recipe-maintainers:
    - danielnachun
