context:
  version: "41.7.2"

package:
  name: vercel-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/vercel/-/vercel-${{ version }}.tgz
  sha256: 0c580414f235d99da11e1bfb5bf8dd0ec0cedd8e6d0b5f9c71bb5f6c399a09c6

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - esbuild
    - nodejs

tests:
  - script:
      - vercel help 2>&1 | grep -q "Vercel CLI ${{ version }}"

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: "Vercel's frontend cloud gives developers frameworks, workflows, and infrastructure to build a faster, more personalized web."
  homepage: https://github.com/vercel/vercel
  repository: https://github.com/vercel/vercel

extra:
  recipe-maintainers:
    - danielnachun
